</div>
</div
</body>
<footer>
    <div class="row">
        <div class="col-lg-12">
            <div class="col-lg-12 col-md-12" style="background: #EDEFF1 none repeat scroll 0% 0%;">
                <div class="container">
                    <!--                    <div class="col-lg-3">
                                            <div class="cuadro_intro_hover " style="background-color:#cccccc;">
                                                <p style="text-align:center; margin-top:20px;">
                                                    <img src="http://placehold.it/500x330" class="img-responsive" alt="">
                                                </p>
                                                <div class="caption">
                                                    <div class="blur"></div>
                                                    <div class="caption-text">
                                                        <h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">THIS IS H3</h3>
                                                        <p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
                                                        <a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-3">
                                            <div class="cuadro_intro_hover " style="background-color:#cccccc;">
                                                <p style="text-align:center; margin-top:20px;">
                                                    <img src="http://placehold.it/500x330" class="img-responsive" alt="">
                                                </p>
                    
                                                <div class="caption">
                                                    <div class="blur"></div>
                                                    <div class="caption-text">
                                                        <h3 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px;">THIS IS H3</h3>
                                                        <p>Loren ipsum dolor si amet ipsum dolor si amet ipsum dolor...</p>
                                                        <a class=" btn btn-default" href="#"><span class="glyphicon glyphicon-plus"> INFO</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>-->
                    <div class="col-lg-3 col-md-6">
                        <h3>Categories:</h3>
                        <ul>
                            <?php
                            $navbar = new Application_Model_Category();
                            $rubrique = $navbar->getRubrique();
                            foreach ($rubrique as $key => $val) {
                                ?>
                                <li><a href='#'><?php echo $val['label_category']; ?> </a></li>
                            <?php }
                            ?>
                        </ul>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h3>Contact:</h3>
                        <p>Une question ? Contacter Nous :</p>
                        <p><a href="<?= $this->url(array('controller' => 'index', 'action' => 'contact'), null, true); ?>" title="Contact me!"><i class="fa fa-envelope"></i> Contact</a></p>
                        <h3>Retrouver nous sur:</h3>
                        <a href="<?= $data['link_twitter']; ?>" id="gh" target="_blank" title="Twitter"><span class="fa-stack fa-lg">
                                <i class="fa fa-square-o fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x"></i>
                            </span>
                            Twitter</a>
                    </div>
                    <br/>
                    <div id="fb-root"></div>
                    <script>(function (d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id))
                                return;
                            js = d.createElement(s);
                            js.id = id;
                            js.src = "https://connect.facebook.net/fr_fr/all.js#xfbml=1";
                            fjs.parentNode.insertBefore(js, fjs);
                        }(document, 'script', 'facebook-jssdk'));</script>

                    <div class="fb-like" data-href="<?= $data['link_facebook']; ?>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

                    <a href="<?= $data['link_twitter']; ?>" class="twitter-share-button" data-url="">Tweet</a>
                    <script>!function (d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
                            if (!d.getElementById(id)) {
                                js = d.createElement(s);
                                js.id = id;
                                js.src = p + '://platform.twitter.com/widgets.js';
                                fjs.parentNode.insertBefore(js, fjs);
                            }
                        }(document, 'script', 'twitter-wjs');</script>

                    <div class="g-plusone" data-annotation="inline" data-width="300" data-href=""></div>
                    <script type="text/javascript">
                        (function () {
                            var po = document.createElement('script');
                            po.type = 'text/javascript';
                            po.async = true;
                            po.src = 'https://apis.google.com/js/platform.js';
                            var s = document.getElementsByTagName('script')[0];
                            s.parentNode.insertBefore(po, s);
                        })();
                    </script>
                    <br/>

                    <hr>
                    <p>Copyright © Your Website | <a href="">Privacy Policy</a> | <a href="">Terms of Use</a></p>
                    </footer>
                    <script src="//tinymce.cachefly.net/4.2/tinymce.min.js"></script>
                    <script>tinymce.init({selector: 'textarea', menubar : false,statusbar : true

});</script>
                    <script src='https://www.google.com/recaptcha/api.js'></script>
                    <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
                    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
                    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/jquery.js"); ?>"></script>
                    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/bootstrap.js"); ?>"></script>
                    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/myScript.js"); ?>"></script>
                    <script type="text/javascript" src="<?php echo $this->baseUrl("/js/lightbox-plus-jquery.min.js"); ?>"></script>

                    <script>
                        $(document).ready(function () {

                            $(".dropdown").hover(
                                    function () {
                                        $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                                        $(this).toggleClass('open');
                                    },
                                    function () {
                                        $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                                        $(this).toggleClass('open');
                                    }
                            );

                        });
                        $(".dropdown-toggleDEFAULT").on('mouseover', function () {
                            $(".open").attr("class", "dropdown");
                            var status = $(this).parent().attr("class");
                            if (status === "dropdown") {
                                $(this).parent().attr("class", "dropdown open");
                            } else {
                                $(this).parent().attr("class", "dropdown");
                            }
                        });
                        $(".containerDEFAULT").hover(function () {
                            $(".open").attr("class", "dropdown");
                            var status = $(this).parent().attr("class");
                            if (status === "dropdown") {
                                $(this).parent().attr("class", "dropdown open");
                            } else {
                                $(this).parent().attr("class", "dropdown");
                            }
                        });
                        //PASSWORD
                        $("input[type=password]").keyup(function () {
                            var ucase = new RegExp("[A-Z]+");
                            var lcase = new RegExp("[a-z]+");
                            var num = new RegExp("[0-9]+");

                            if ($("#password1").val().length >= 8) {
                                $("#8char").removeClass("glyphicon-remove");
                                $("#8char").addClass("glyphicon-ok");
                                $("#8char").css("color", "#00A41E");
                            } else {
                                $("#8char").removeClass("glyphicon-ok");
                                $("#8char").addClass("glyphicon-remove");
                                $("#8char").css("color", "#FF0004");
                            }

                            if (ucase.test($("#password1").val())) {
                                $("#ucase").removeClass("glyphicon-remove");
                                $("#ucase").addClass("glyphicon-ok");
                                $("#ucase").css("color", "#00A41E");
                            } else {
                                $("#ucase").removeClass("glyphicon-ok");
                                $("#ucase").addClass("glyphicon-remove");
                                $("#ucase").css("color", "#FF0004");
                            }

                            if (lcase.test($("#password1").val())) {
                                $("#lcase").removeClass("glyphicon-remove");
                                $("#lcase").addClass("glyphicon-ok");
                                $("#lcase").css("color", "#00A41E");
                            } else {
                                $("#lcase").removeClass("glyphicon-ok");
                                $("#lcase").addClass("glyphicon-remove");
                                $("#lcase").css("color", "#FF0004");
                            }

                            if (num.test($("#password1").val())) {
                                $("#num").removeClass("glyphicon-remove");
                                $("#num").addClass("glyphicon-ok");
                                $("#num").css("color", "#00A41E");
                            } else {
                                $("#num").removeClass("glyphicon-ok");
                                $("#num").addClass("glyphicon-remove");
                                $("#num").css("color", "#FF0004");
                            }

                            if ($("#password1").val() == $("#password2").val()) {
                                $("#pwmatch").removeClass("glyphicon-remove");
                                $("#pwmatch").addClass("glyphicon-ok");
                                $("#pwmatch").css("color", "#00A41E");
                            } else {
                                $("#pwmatch").removeClass("glyphicon-ok");
                                $("#pwmatch").addClass("glyphicon-remove");
                                $("#pwmatch").css("color", "#FF0004");
                            }
                        });
                        $(document).ready(function () {
                            $(".dropdown").hover(
                                    function () {
                                        $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                                        $(this).toggleClass('open');
                                    },
                                    function () {
                                        $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                                        $(this).toggleClass('open');
                                    }
                            );
                        });

                        $(document).on('click', '.number-spinner button', function () {
                            var btn = $(this),
                                    oldValue = btn.closest('.number-spinner').find('input').val().trim(),
                                    newVal = 0
                            var max = $("#qteMax").text();

                            if (btn.attr('data-dir') == 'up') {

                                newVal = parseInt(oldValue) + 1;
                                if (newVal > 10) {
                                    $('.bg-danger').show();
                                } else {
                                    $('.bg-danger').hide();
                                }
                                if (max != 10) {
                                    if (newVal > max) {
                                        $('.bg-danger').show();
                                    } else {
                                        $('.bg-danger').hide();
                                    }
                                }
                            } else {
                                if (oldValue > 1) {
                                    newVal = parseInt(oldValue) - 1;
                                    if (newVal > 10) {
                                        $('.bg-danger').show();
                                    } else {
                                        $('.bg-danger').hide();
                                    }
                                    if (max != 10) {
                                        if (newVal > max) {
                                            $('.bg-danger').show();
                                        } else {
                                            $('.bg-danger').hide();
                                        }
                                    }
                                } else {
                                    newVal = 1;
                                }
                            }
                            $("#qte_product").val(newVal);
                            btn.closest('.number-spinner').find('input').val(newVal);
                            var qte = $("#quantite").text("Quantité : " + newVal);

                        });

                        $(document).on('keyup', '#number_product', function () {
                            var max = $("#qteMax").text();
                            var btn = $(this).val();
                            $("#qte_product").val(btn);
                            if (btn > 10) {
                                $('.bg-danger').show();
                            } else {
                                $('.bg-danger').hide();
                            }
                            if (max != 10) {

                                if (btn > max) {
                                    $('.bg-danger').show();
                                } else {
                                    $('.bg-danger').hide();
                                }
                            }
                            var qte = $("#quantite").text("Quantité : " + btn);

                        });

                    </script>
                    </html>