<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $website_name; ?></title>
        <link rel="icon" type="image/png" href="data:image/<?= $data['name_favicon'] . ';base64,' . $data['favicon'] ?>" />
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/header.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/footer.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/product.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/style.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/lightbox.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/panier.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/paiement.css'); ?>"/>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-default" role="navigation" style="max-height: 51.3px;">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" style="" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>"><img src="data:image/<?= $data['name_logo'] . ';base64,' . $data['logo'] ?>" class="navbar-brand" style="padding:0;" /></a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                        <ul class="nav navbar-nav">
                            <li class="dropdown mega-dropdown active">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Catégories <span class="caret"></span></a>				
                                <div style="display: none;" class="dropdown-menu mega-dropdown-menu">
                                    <div class="container-fluid">
                                        <div class="tab-content">
                                            <?php
                                            $navbar = new Application_Model_Category();
                                            $rubrique = $navbar->getRubrique();
                                            $ssrubrique = $navbar->getSousRubrique();
                                            $ssrubrique = $navbar->convertImageSousRubrique($ssrubrique);
                                            $i = 0;
                                            foreach ($rubrique as $key => $val) {
                                                if ($i == 0) {
                                                    echo"<div class='tab-pane active' id='" . $val['label_category'] . "'>";
                                                } else {
                                                    echo"<div class='tab-pane' id='" . $val['label_category'] . "'>";
                                                }
                                                echo"<ul class='nav-list list-inline'>";
                                                foreach ($ssrubrique as $s) {
                                                    if ($s['parent'] == $val['id_category']) {
                                                        ?>
                                                        <li><a method="GET" href="<?php echo $this->url(array('controller' => 'category', 'action' => 'index', 'type' => $s['id_category']), null, true); ?>"> <img width="80" height="80px" src="data:image/<?php echo $s['type'] . ' ;base64,' . $s['img64'] ?>" alt=""><span><?php echo $s['label_category']; ?></span></a></li>
                                                        <?php
                                                    }
                                                }
                                                echo "</ul></div> ";
                                                $i++;
                                            }
                                            ?>
                                        </div>
                                    </div>
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-tabs" role="tablist">
                                        <?php
                                        $i = 0;
                                        foreach ($rubrique as $key => $val) {
                                            if ($i == 0) {
                                                echo"<li class='active'><a href='#" . $val['label_category'] . "' role='tab' data-toggle='tab'>" . $val['label_category'] . "</a></li>";
                                            } else {
                                                echo"<li><a href='#" . $val['label_category'] . "' role='tab' data-toggle='tab'>" . $val['label_category'] . "</a></li>";
                                            }
                                            $i++;
                                        }
                                        ?>
                                    </ul>                    
                                </div>				
                            </li>
                        </ul>
                        <form method="GET" class="navbar-form navbar-left" role="search" action="<?php echo $this->url(array('controller' => 'article', 'action' => 'search', 'page' => '1'), null, true); ?>" style="width: 50%; margin-left: 15%!important;">
                            <div class="input-group col-md-12">
                                <input type="text" class="search-query form-control" name="search" placeholder="rechercher"/>
                                <span class="input-group-btn">
                                    <button class="btn btn-danger" type="submit">
                                        <span class=" glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>

                        </form>
                        <ul class="nav navbar-nav navbar-right">
                            <?php if ($this->lvl == 0): ?>
                                <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), null, true); ?>">Mon compte</a></li>
                                <?php
                            else:
                                if (isset($_SESSION['panier'])) {


                                    $session = $_SESSION['panier'];
                                    if (!empty($session)) {
                                        $tab = array();
                                        foreach ($session as $key => $val) {

                                            $tab[] = $key;
                                        }
                                        $sell = new Application_Model_Sell();

                                        $panier = $sell->getArticle(null, $tab);
                                        $panier = $sell->convertImageSousRubrique($panier);
                                    } else {
                                        $session = null;
                                        $panier = null;
                                    }
                                }
                                ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                        <span class="glyphicon glyphicon-shopping-cart"></span> <span id="panier" nb="<?php echo count($session); ?>">
                                        <?php
                                        if (count($session) > 0) {
                                            if (count($session) == 1) {
                                                echo "1 produit";
                                            } else {
                                                echo count($session) . " produits";
                                            }
                                        } else {
                                            echo "Panier";
                                        }
                                        ?></span>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-cart" role="menu">
                                        <?php
                                        if ($panier != null && $session != null) {
                                            foreach ($panier as $key => $val) {
                                                ?>
                                                <li>
                                                    <span class="item" id="item-<?php echo $val['id_sell']; ?>">
                                                        <span class="item-left">
                                                            <img  style="max-height: 50px; max-width: 50px;" src="data:image/<?php echo $val['type'] . ' ;base64,' . $val['img64'] ?>" />
                                                            <span class="item-info">
                                                                <span><center><a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'product', "fiche" => $val['id_sell']), null, true); ?>"><?php echo $val['title']; ?></a></center></span>
                                                                <span>Prix : <?php echo $val['price'] . " € "; ?> </span>
                                                                <span id="qte-panier-<?php echo $val['id_sell']; ?>">Quantité : <?php echo $session[$val['id_sell']]; ?></span>
                                                            </span>
                                                        </span>
                                                    </span>
                                                </li>
                                            <?php } ?>
                                            <li class="divider"></li>
                                            <li><a class="text-center" id="voir-panier"  href="<?php echo $this->url(array('controller' => 'panier', 'action' => 'index'), null, true); ?>">Voir mon panier</a></li>
                                            <li id="panier-vide" style="display:none;">
                                                <span class="item">
                                                    <span class="item-container">

                                                        <span class="item-info">
                                                            <center> Vide</center>
                                                        </span>
                                                    </span>
                                                </span>
                                            </li>
                                            
                                        <?php } else { ?>
                                            <li>
                                                <span class="item">
                                                    <span class="item-container">

                                                        <span class="item-info">
                                                            <center> Vide</center>
                                                        </span>
                                                    </span>
                                                </span>
                                            </li>
                                            <li class="divider" style="display:none;"></li>
                                            <li class="div-panier"  style="display:none;">
                                                <a class="text-center" id="voir-panier"  href="<?php echo $this->url(array('controller' => 'panier', 'action' => 'index'), null, true); ?>">Voir mon panier</a>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><?= $this->firstname . " " . $this->lastname; ?><span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'parameter'), null, true); ?>"><span class="glyphicon glyphicon-wrench"></span> Paramètre de mon compte</a></li>
                                        <li class="divider">
                                        </li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'article'), null, true); ?>"><span class="glyphicon glyphicon-wrench"></span> Mes articles</a></li>
                                        <li class="divider"></li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'destroy'), null, true); ?>">
                                                <span class="glyphicon glyphicon-off"></span>
                                                Se Déconnecter</a></li>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>

        </header>
        <div class="main">
            <div class = "container" style="margin-bottom: 10px;">               
