<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Snippet - Bootsnipp.com</title>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/header.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/footer.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/product.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/style.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/lightbox.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/panier.css'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/paiement.css'); ?>"/>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>"></a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                        <ul class="nav navbar-nav">
                            <li class="dropdown mega-dropdown active">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Catégories <span class="caret"></span></a>				
                                <div style="display: none;" class="dropdown-menu mega-dropdown-menu">
                                    <div class="container-fluid">
                                        <div class="tab-content">
                                            <?php
                                            $navbar = new Application_Model_Category();
                                            $rubrique = $navbar->getRubrique();
                                            $ssrubrique = $navbar->getSousRubrique();
                                            $ssrubrique = $navbar->convertImageSousRubrique($ssrubrique);
                                            $i = 0;
                                            foreach ($rubrique as $key => $val) {
                                                if ($i == 0) {
                                                    echo"<div class='tab-pane active' id='" . $val['label_category'] . "'>";
                                                } else {
                                                    echo"<div class='tab-pane' id='" . $val['label_category'] . "'>";
                                                }
                                                echo"<ul class='nav-list list-inline'>";
                                                foreach ($ssrubrique as $s) {
                                                    if ($s['parent'] == $val['id_category']) {
                                                        ?>
                                                        <li><a method="GET" href="<?php echo $this->url(array('controller' => 'category', 'action' => 'index', 'type' => $s['id_category']), null, true); ?>"> <img width="80" height="80px" src="data:image/<?php echo $s['type'] . ' ;base64,' . $s['img64'] ?>" alt=""><span><?php echo $s['label_category']; ?></span></a></li>
                                                    <?php
                                                    }
                                                }
                                                echo "</ul></div> ";
                                                $i++;
                                            }
                                            ?>
                                        </div>
                                    </div>
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-tabs" role="tablist">
                                        <?php
                                        $i = 0;
                                        foreach ($rubrique as $key => $val) {
                                            if ($i == 0) {
                                                echo"<li class='active'><a href='#" . $val['label_category'] . "' role='tab' data-toggle='tab'>" . $val['label_category'] . "</a></li>";
                                            } else {
                                                echo"<li><a href='#" . $val['label_category'] . "' role='tab' data-toggle='tab'>" . $val['label_category'] . "</a></li>";
                                            }
                                            $i++;
                                        }
                                        ?>
                                    </ul>                    
                                </div>				
                            </li>
                        </ul>
                        <form method="GET" class="navbar-form navbar-left" role="search" action="<?php echo $this->url(array('controller' => 'article', 'action' => 'search', 'page' => '1'), null, true); ?>" style="width: 50%; margin-left: 15%!important;">
                            <div class="input-group col-md-12">
                                <input type="text" class="search-query form-control" name="search" placeholder="rechercher"/>
                                <span class="input-group-btn">
                                    <button class="btn btn-danger" type="button">
                                        <span class=" glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>

                        </form>
                        <ul class="nav navbar-nav navbar-right">
                            <?php if ($this->lvl == 0): ?>
                                <li> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), null, true); ?>">Mon compte</a></li>
<?php else: ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="glyphicon glyphicon-shopping-cart"></span> 7 - Articles<span class="caret"></span></a>
                                    <ul class="dropdown-menu dropdown-cart" role="menu">
                                        <li>
                                            <span class="item">
                                                <span class="item-left">
                                                    <img src="http://lorempixel.com/50/50/" alt="" />
                                                    <span class="item-info">
                                                        <span>Item name</span>
                                                        <span>23$ Qte: 1</span>
                                                    </span>
                                                </span>
                                                <span class="item-right">
                                                    <button class="btn btn-xs btn-danger pull-right">x</button>
                                                </span>
                                            </span>
                                        </li>
                                        <li>
                                            <span class="item">
                                                <span class="item-left">
                                                    <img src="http://lorempixel.com/50/50/" alt="" />
                                                    <span class="item-info">
                                                        <span>Item name</span>
                                                        <span>23$</span>
                                                    </span>
                                                </span>
                                                <span class="item-right">
                                                    <button class="btn btn-xs btn-danger pull-right">x</button>
                                                </span>
                                            </span>
                                        </li>
                                        <li>
                                            <span class="item">
                                                <span class="item-left">
                                                    <img src="http://lorempixel.com/50/50/" alt="" />
                                                    <span class="item-info">
                                                        <span>Item name</span>
                                                        <span>23$</span>
                                                    </span>
                                                </span>
                                                <span class="item-right">
                                                    <button class="btn btn-xs btn-danger pull-right">x</button>
                                                </span>
                                            </span>
                                        </li>
                                        <li>
                                            <span class="item">
                                                <span class="item-left">
                                                    <img src="http://lorempixel.com/50/50/" alt="" />
                                                    <span class="item-info">
                                                        <span>Item name</span>
                                                        <span>23$</span>
                                                    </span>
                                                </span>
                                                <span class="item-right">
                                                    <button class="btn btn-xs btn-danger pull-right">x</button>
                                                </span>
                                            </span>
                                        </li>
                                        <li class="divider"></li>
                                        <li><a class="text-center" href="">Voir mon panier</a></li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><?= $this->firstname . " " . $this->lastname; ?><span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'parameter'), null, true); ?>"><span class="glyphicon glyphicon-wrench"></span> Paramètre de mon compte</a></li>
                                        <li class="divider">
                                        </li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'article'), null, true); ?>"><span class="glyphicon glyphicon-wrench"></span> Mes articles</a></li>
                                        <li class="divider"></li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'destroy'), null, true); ?>">
                                                <span class="glyphicon glyphicon-off"></span>
                                                Se Déconnecter</a></li>
                                    </ul>
                                </li>
<?php endif; ?>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>

        </header>
        <div class="main">
            <div class = "container" style="margin-bottom: 10px;">               
