<?php $p = $this->produit[0]; ?>
<div class = "col-md-2"></div>
<div class = "col-md-8">

        <form style="max-width: 768px!important;" method="POST" action="<?= $this->url(array('controller' => 'article', 'action' => 'modify','fiche'=>$p['id_sell'] ), null, true); ?>" enctype="multipart/form-data"  name="Login_Form" class="form-signin">       
            <h3 class="form-signin-heading"><center>Modifier votre produit</center></h3>

            <hr class="colorgraph">
         
                <div class="col-xs-6">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="control-label">Titre du produit</label>
                            <input  maxlength="50" type="text" name="title"  class="form-control" placeholder="Le titre de votre produit" value="<?php echo $p['title']; ?>"  autocomplete="off"/>
                        </div>
                        <div class="form-group">

                            <label class="control-label">Image du produit</label>
                            <span class="file-input btn btn-block btn-primary btn-file">
                                Uploader l'image de votre produit <input type="file" id='image'  name="image" >
                            </span>
                              <a class="example-image-link" href="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" data-lightbox="example-1">
                            <img  style="max-height: 319px; max-width: 259px;"  src="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" /></a>
                            
                            
                        </div>
                       <div>
                                Sous-Rubrique : <?= $this->sr; ?>
                            </div>
                    </div>
                </div>
           
       
                <div class="col-xs-6">
                    <div class="col-md-12">
                     
                        <div class="form-group">
                            <label class="control-label">Description courte (max: 100 caractères)</label>
                            <input maxlength="100" type="text" name="description_courte"  value="<?php echo $p['description_courte']; ?>"  class="form-control" placeholder="Description courte" />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Description longue</label>
                            <textarea name="description" id="productDescription" id="toto" ><?php echo $p['description']; ?></textarea>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <label class="control-label">Quantité</label>
                                <input name="quantity"  value="<?php echo $p['quantity']; ?>" class="form-control"  />  </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <label class="control-label">Prix</label>
                                <div class="input-group">
                                    <span class="input-group-addon">€</span>
                                    <input data-fv-field="amount" class="form-control" name="price" value="<?php echo $p['price']; ?>"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <table class="table table-bordered table-hover">
                                <tr><td class="info"><center>Rubrique</center></td></tr>
                                <?php foreach ($this->category as $value):?>
                                    <tr><td class="clickListRubrique active" data="category-<?= $value['id_category']; ?>"><center><?= $value['label_category']; ?></center></td></tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <?php
                            foreach ($this->category as $value) {
                                ?> 
                                <table style="display:none;" class="table table-bordered table-hover sous-category" id="category-<?= $value['id_category']; ?>">
                                    <tr><td class="info"><center>Sous Rubrique : <?= $value['label_category']; ?></center></td></tr>
                                    <?php
                                    foreach ($this->souscategory as $key => $ssrubrique) {
                                        if ($ssrubrique['parent'] == $value['id_category']) {
                                            ?>
                                            <tr>
                                                <td class="active select-sous-category" data="<?= $ssrubrique['id_category']; ?>"><?= $ssrubrique['label_category']; ?></td>
                                            </tr>
                                            <?php
                                        }
                                    }
                                    ?>
                                </table>
                            <?php }
                            ?>
                            <span id="sous-rubrique-choisi" sous-rubrique="" id-sous-rubrique="" rubrique="" style="display:none;"></span>
                            <input type="hidden" name="sous-rubrique-hidden" id="sous-rubrique-cacher" value="">
                        </div>
                        
                    </div>
                </div>
            <div class="col-md-12">
                            <hr class="colorgraph">
                            <div class="row">
                                <div class="col-xs-12">
                                    <button class="btn btn-lg btn-primary btn-block nextBtn" id="reviewProduct" type="submit">Modifier le produit</button>  			
                                </div>
                            </div>
                        </div>
        </form>		
 
</div>
