
<?php $p = $this->produit[0]; ?>
<div class="container-fluid">
    <div class="content-wrapper">	
        <div class="item-container">	
            <form action="<?= $this->url(array('controller' => 'article', 'action' => 'modify','fiche'=>$p['id_sell'] ), null, true); ?>" method="POST" enctype="multipart/form-data" >
            <div class="container">	
                <div class="col-md-5">
                    <div class="product col-md-7 service-image-left">
                    
                            <a class="example-image-link" href="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" data-lightbox="example-1">
                            <img  style="max-height: 319px; max-width: 259px;"  src="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" /></a>
                        
                    </div>

                    <input type="file" name="image" enctype="multipart/form-data" />
                    <input type="hidden" name="MAX_FILE_SIZE" value="6000" />
                </div>

                <div class="col-md-7">
                    <div class="product-title">Titre :<input type="text" maxlength="50" name="title" value="<?php echo $p['title']; ?>" /></div>
                    <div class="product-desc">Description courte :<input type="text" maxlength="100" name="description_courte" value="<?php echo $p['description_courte']; ?>" /></div>

                    <hr>
                    <div class="container">
                        <div class="col-md-2">
                            <div class="product-price">Prix :<input type="text"   name="price" value="<?php echo $p['price']; ?>" required=""/></div>
                        </div>      
                    </div> 
                    <div class="container">
                        <div class="col-md-2">
                            Quantité : 
                            <div class="input-group number-spinner">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" data-dir="dwn"><span class="glyphicon glyphicon-minus"></span></button>
                                </span>
                                <input type="number" class="form-control text-center" max="999" min="0" name="quantity" value="<?php echo $p['quantity']; ?>">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" data-dir="up"><span class="glyphicon glyphicon-plus"></span></button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="container-fluid">		
                <div class="col-md-12 product-info">
                    <ul id="myTab" class="nav nav-tabs nav_tabs">
                        <li class="active"><a href="#service-one" data-toggle="tab">DESCRIPTION</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade in active" id="service-one">

                            <section class="container product-info">
                               <textarea name="description" id="" cols="150" rows="10"><?php echo $p['description']; ?></textarea>
                            </section>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
                <input type="submit" value="Enregistrer" />
            </form>
        </div>
    </div>