<?php $p = $this->produit[0]; ?>
<div class="container-fluid">
    <div class="content-wrapper">	
        <div class="item-container">	
            <div class="container">	
                <div class="col-md-5">
                    <div class="product col-md-7 service-image-left">
                        <center>
                            <a class="example-image-link" href="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" data-lightbox="example-1">
                                <img  style="max-height: 319px; max-width: 259px;"  src="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" />
                            </a>
                        </center>
                    </div>
                </div>

                <div class="col-md-7">
                    <div class="product-title"><?php echo $p['title']; ?></div>
                    <div class="product-desc"><?php echo $p['description_courte']; ?></div>

                    <hr>

                    <div class="col-md-3">
                        <div class="product-price"><?php echo number_format($p['price'], 2, ',', ' '); ?> €</div>
                    </div>
                    <?php if ($p['quantity'] > 0) { ?>
                        <div class="col-md-3"><div class="product-quantity"><?php
                                if ($p['quantity'] > 10) {
                                    echo "Plus de <span id='qteMax'>10</span> disponibles";
                                } else {
                                    if ($p['quantity'] == 1) {
                                        echo "<span id='qteMax'>1</span> disponible";
                                    } else {
                                        echo "<span id='qteMax'>" . $p['quantity'] . "</span> disponibles";
                                    }
                                }
                                ?>

                            </div>
                        </div>


                        <?php
                        if (isset($_SESSION)) {
                            $rank = $_SESSION['user']['data']['id_rank'];
                            if (($rank == "1" || $rank == 2) && $rank != null) {
                                ?>
                                <div class="container">
                                    <div class="col-md-2">
                                        <div class="input-group number-spinner">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" data-dir="dwn"><span class="glyphicon glyphicon-minus"></span></button>
                                            </span>
                                            <input type="text" class="form-control text-center" id="number_product" value="1">

                                            <span class="input-group-btn">
                                                <button class="btn btn-default" data-dir="up"><span class="glyphicon glyphicon-plus"></span></button>
                                            </span>
                                        </div>
                                        <div style="display: none;" class="bg-danger"><center>Veuiller saisir une quantité inférieur</center></div>
                                    </div>
                                </div>
                                <?php
                            }
                        }
                    }
                    ?>
                    <?php if ($p['quantity'] > 0) { ?>
                        <div class="col-md-2">
                            <div class="container">
                                <div class="row">
                                    <div class="product-stock">En Stock</div> 
                                </div>
                            </div>
                        </div>
                        <div class="container"></div>
                    <?php } else { ?>


                        <div class="container">
                            <div class="row">
                                <div class="product-stock-epuise">Stock Epuisé</div>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="container">
                        <hr>
                        <!-------------Modal---------->
                        <div style="display: none;" id="gridSystemModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                        <h4 class="modal-title" id="gridModalLabel"><?php echo $p['title']; ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container-fluid">
                                            <div class="row">
                                                <div class="col-xs-6 col-md-3">
                                                    <img style="max-height:100px; max-width: 100px;" src="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" alt="">                                             

                                                </div>
                                                <span style="font-weight: bold; color: #009600; font-size: 1.8em;"> Cet article a été ajouté au panier !</span>
                                                <span   id="quantite" style="color: #141414; font-size: 1.6em; display: block; text-transform: capitalize;">Quantité : 1</span>

                                            </div>

                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="row">
                                            <div class="col-md-8">
                                                <div class="col-md-4">
                                                    <form method="GET" action="<?php echo $this->url(array('controller' => 'category', 'action' => 'index', 'type' => $p['id_category']), null, true); ?>">
                                                        <button type="submit" class="btn btn-default">Poursuivre mes achats</button>
                                                    </form>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <form method="POST" action="<?php echo $this->url(array('controller' => 'panier', 'action' => 'index'), null, true); ?>">
                                                    <button type="submit" class="btn btn-primary">Voir mon panier</button>
                                                </form>
                                            </div>
                                        </div>

                                    </div>
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->
                        <?php
                        if (isset($_SESSION)) {
                            $rank = $_SESSION['user']['data']['id_rank'];
                            if (($rank == "1" || $rank == 2) && $rank != null) {
                                if ($p['quantity'] > 0) { 
                                ?>
                                <div class="bs-example bs-example-padded-bottom">
                                    <input type="hidden" name="id_product" value="<?php echo $p['id_sell']; ?>">
                                    <button type="button" class="btn btn-success btn-lg commander" data-toggle="modal" data-target="#gridSystemModal">
                                        Commander
                                    </button>
                                </div><!-- /example -->
                                <?php }} else {
                                ?>
                                <div class="bs-example bs-example-padded-bottom">
                                    <form method="POST" action="<?php echo $this->url(array('controller' => 'user', 'action' => 'index'), null, true); ?>">
                                        <button type="submit" class="btn btn-success btn-lg">
                                            Connecter vous pour commander
                                        </button>
                                    </form>
                                </div><!-- /example -->
                            <?php
                            }
                        }
                        ?>

                    </div>
                </div> 
            </div>
            <div class="container-fluid">		
                <div class="col-md-12 product-info">
                    <ul id="myTab" class="nav nav-tabs nav_tabs">

                        <li class="active"><a href="#service-one" data-toggle="tab">DESCRIPTION</a></li>
                        <li><a href="#service-two" data-toggle="tab">VENDEUR</a></li>

                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade in active" id="service-one">

                            <section class="container product-info">
<?php echo $p['description']; ?>
                            </section>

                        </div>
                        <div class="tab-pane fade" id="service-two">

                            <section class="container">
                                <!--   <div class="row">
                                      <div class="col-xs-12 col-sm-6 col-md-6">-->
                                <table class="table">
                                    <tr>
                                        <td>Pseudo</td>
                                        <td><?php echo $p['login_user']; ?></td>
                                    </tr>
                                    <tr>
                                        <td>E-mail</td>
                                        <td><?php echo $p['mail_user']; ?></td>
                                    </tr>
                                </table>
                                <!--</div>
                            </div>-->
                            </section>

                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>