<div class="container-fluid">
    <div class="content-wrapper">	
        <div class="item-container">	
            <div class="container">	
                <div class="col-md-5">
                    <div class="product col-md-7 service-image-left">
                        <center>
                            <a class="example-image-link" href="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png" data-lightbox="example-1">
                                <img style="padding-top: 30%;"   width="240" height="auto" src="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png" alt="" ></img></a>
                        </center>
                    </div>

                    <div class="container service1-items col-sm-5 col-md-5 pull-left">
                        <center>
                            <a id="item-1" class="service1-item" data-lightbox="example-set" href="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png">
                                <img src="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png" alt=""></img>
                            </a>
                            <a id="item-2" class="service1-item" data-lightbox="example-set" href="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png">
                                <img src="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png" alt=""></img>
                            </a>
                            <a id="item-3" class="service1-item" data-lightbox="example-set" href="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png">
                                <img src="http://www.corsair.com/Media/catalog/product/g/s/gs600_psu_sideview_blue_2.png" alt=""></img>
                            </a>
                        </center>
                    </div>
                </div>

                <div class="col-md-7">
                    <div class="product-title">Corsair GS600 600 Watt PSU</div>
                    <div class="product-desc">The Corsair Gaming Series GS600 is the ideal price/performance choice for mid-spec gaming PC</div>

                    <hr>
                    <div class="col-md-2">
                        <div class="product-price">200 €</div></div>
                    <div class="col-md-2">   Plus de 10 disponible</div>
                    <div class="container">
                        <div class="col-md-2">
                            <div class="input-group number-spinner">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" data-dir="dwn"><span class="glyphicon glyphicon-minus"></span></button>
                                </span>
                                <input type="text" class="form-control text-center" value="1">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" data-dir="up"><span class="glyphicon glyphicon-plus"></span></button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="container">
                            <div class="row">
                                <div class="product-stock">En Stock</div> 
                            </div>
                        </div>
                    </div>


                    <div class="container">
                        <div class="row">
                            <div class="product-stock-epuise">Stock Epuisé</div>
                        </div>
                    </div>
             
                    <div class="container">
                        <hr>
                        <div class="btn-group cart">
                            <button type="button" class="btn btn-success">
                                Ajouter au Panier
                            </button>

                        </div>
                        <div class="btn-group wishlist">
                            <button type="button" class="btn btn-danger">
                                Acheter Immédiatement
                            </button>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="container-fluid">		
                <div class="col-md-12 product-info">
                    <ul id="myTab" class="nav nav-tabs nav_tabs">

                        <li class="active"><a href="#service-one" data-toggle="tab">DESCRIPTION</a></li>
                        <li><a href="#service-two" data-toggle="tab">VENDEUR</a></li>

                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade in active" id="service-one">

                            <section class="container product-info">
                                The Corsair Gaming Series GS600 power supply is the ideal price-performance solution for building or upgrading a Gaming PC. A single +12V rail provides up to 48A of reliable, continuous power for multi-core gaming PCs with multiple graphics cards. The ultra-quiet, dual ball-bearing fan automatically adjusts its speed according to temperature, so it will never intrude on your music and games. Blue LEDs bathe the transparent fan blades in a cool glow. Not feeling blue? You can turn off the lighting with the press of a button.

                                <h3>Corsair Gaming Series GS600 Features:</h3>
                                <li>It supports the latest ATX12V v2.3 standard and is backward compatible with ATX12V 2.2 and ATX12V 2.01 systems</li>
                                <li>An ultra-quiet 140mm double ball-bearing fan delivers great airflow at an very low noise level by varying fan speed in response to temperature</li>
                                <li>80Plus certified to deliver 80% efficiency or higher at normal load conditions (20% to 100% load)</li>
                                <li>0.99 Active Power Factor Correction provides clean and reliable power</li>
                                <li>Universal AC input from 90~264V — no more hassle of flipping that tiny red switch to select the voltage input!</li>
                                <li>Extra long fully-sleeved cables support full tower chassis</li>
                                <li>A three year warranty and lifetime access to Corsair’s legendary technical support and customer service</li>
                                <li>Over Current/Voltage/Power Protection, Under Voltage Protection and Short Circuit Protection provide complete component safety</li>
                                <li>Dimensions: 150mm(W) x 86mm(H) x 160mm(L)</li>
                                <li>MTBF: 100,000 hours</li>
                                <li>Safety Approvals: UL, CUL, CE, CB, FCC Class B, TÜV, CCC, C-tick</li>
                            </section>

                        </div>
                        <div class="tab-pane fade" id="service-two">

                            <section class="container">
                                <!--   <div class="row">
                                      <div class="col-xs-12 col-sm-6 col-md-6">-->
                                <table class="table">
                                    <tr>
                                        <td>Pseudo</td>
                                        <td>Alibaba</td>
                                    </tr>
                                    <tr>
                                        <td>Coordonnée</td>
                                        <td> 3 rue petit pas</td>
                                    </tr>
                                    <tr>
                                        <td>E-mail</td>
                                        <td>alibaba@40voleurs.com</td>
                                    </tr>
                                </table>
                                <!--</div>
                            </div>-->
                            </section>

                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>