<div class="row">
    <div class="col-xs-12 col-sm-3">
        <br>
        <!-- START CONTENT ITEM -->
        
    </div>
    <div class="col-md-9">
        <div class="row">
            <?php foreach ($this->produit as $p) { 
               
                ?>
            <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'product',"fiche"=> $p['id_sell']),null,true); ?>">
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        
                        <img style="min-height: 250px; max-height: 250px;"  src="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" />
                        
                        <div class="caption">
                            <h4 class="pull-right"><?php echo $p['price']." €"; ?></h4>
                            <h4><a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'product',"fiche"=> $p['id_sell']),null,true); ?>"><?php echo $p['title']; ?></a>
                            </h4>
                            <p><?php echo $p['description_courte']; ?></p>
                        </div>
                    </div>
                </div>
            </a>
            <?php } ?>
        </div>
    </div>
    <div class="container">
        <ul class="pagination">
            <?php echo $this->pagination; ?>
        </ul>
    </div>
    
</div>