<div class="row">
    <div class="col-xs-12 col-sm-3">
					<br>
					<!-- START CONTENT ITEM -->
					<div class="row">
						<div class="col-xs-12">
							<div class="well well-small">
								<ul class="nav nav-list">
									<li class="nav-header">Brands</li>
									<li class="active"><a href="#"><span class="glyphicon glyphicon-ok"></span> Brand A</a></li>
									<li><a href="#"><span class="glyphicon glyphicon-ok"></span> Brand B</a></li>
									<li class="active"><a href="#"><span class="glyphicon glyphicon-ok"></span> Brand C</a></li>
									<hr>
									<li class="nav-header">Price</li>
									<li class="active"><a href="#"><span class="glyphicon glyphicon-ok"></span> € 10 - € 50</a></li>
									<li class="active"><a href="#"><span class="glyphicon glyphicon-ok"></span> € 50 - € 100</a></li>
									<li><a href="#"><span class="glyphicon glyphicon-ok"></span> € 100 - € 250</a></li>
									<hr>
									<li class="nav-header">Color</li>
									<li><a href="#"><span class="glyphicon glyphicon-ok"></span> Orange</a></li>
									<li class="active"><a href="#"><span class="glyphicon glyphicon-ok"></span> Red</a></li>
									<li><a href="#"><span class="glyphicon glyphicon-ok"></span> Yellow</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
    <div class="col-md-9">
        <div class="row">
            <?php foreach ($this->produit as $p) { ?>
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src="http://placehold.it/320x150" alt="">
                    <div class="caption">
                        <h4 class="pull-right">$24.99</h4>
                        <h4><a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'fiche_detail')); ?>"><?php echo $p['label_article']; ?></a>
                        </h4>
                        <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </div>
                   </div>

            <?php } ?>
        </div>
    </div>
</div>