<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1"><small>
                        BESOIN D'AIDE, VOUS AVEZ UNE QUESTION ?</small></h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                   
                            <input type="text" class="form-control" id="name" placeholder="Nom" required="required" />
                        </div>
                         <div class="form-group">
                 
                            <input type="text" class="form-control" id="name" placeholder="Prénom" required="required" />
                        </div>
                        <div class="form-group">
                      
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                <input type="email" class="form-control" id="email" placeholder="Email" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject">
                               Objet du message</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Sélectionner en un :</option>
                                <option value="service">Service Général</option>
                                <option value="suggestions">Suggestion</option>
                                <option value="product">Support</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                           Envoyer un message</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <form>
            <legend><span class="glyphicon glyphicon-globe"></span> Notre siège social</legend>
            <address>
                <strong>Telemaque, Inc.</strong><br>
               75 Boulvard Maupassant<br>
                Paris 75017<br>
                France<br>
                <abbr title="Phone">
                    Tel:</abbr>
               01-48-59-75-45
            </address>
            <address>
                <strong>Notre Email</strong><br>
                <a href="mailto:#">contact@telemaque.fr</a>
            </address>
            </form>
        </div>
    </div>
</div>
