<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <center>
                    <h1 class="h1">
                        <small>
                            <?= $this->error; ?>
                        </small>
                    </h1>
                </center>               
            </div>
        </div>
    </div>
</div>