<div class="col-md-12">
<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12" style="height:30px; text-align:center;  ">        
             <h2 style="margin-top: 0px;">
                    <i>
                        <small>
                            <?= $this->catchphrase ?>
                        </small>
                    </i>
                 </h2>
            </div>
        </div>
    </div>
</div>

    <!--<div class="row carousel-holder">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="margin-bottom: 20px;">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

    </div>-->

    <div class="row">
        <?php foreach ($this->product as $p) { ?>
            <div class="col-sm-3 col-lg-3 col-md-3" style="min-height: 387.8px;">
                <div class="thumbnail" style="min-height: 367.8px; max-height: 367.8px;">
                    <img style="min-height: 250px; max-height: 250px;"  src="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" />
                    <div class="caption">
                        <h4 class="pull-right"><?php echo $p['price'] . " €"; ?></h4>
                        <h4><a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'product', "fiche" => $p['id_sell']), null, true); ?>"><?php echo $p['title']; ?></a>
                        </h4>
                        <p><?php echo $p['description_courte']; ?></p>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>