<div class="col-md-12">
    <div class="jumbotron jumbotron-sm" style="padding-bottom: 20px;padding-top: 20px;opacity: 0.8;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12" style="height:30px; text-align:center;  ">        
             <h2 style="margin-top: 0px;">
                    <i>
                        <small style="text-shadow: 1px 1px #000;">
                            <?= $this->catchphrase ?>
                        </small>
                    </i>
                 </h2>
            </div>
        </div>
    </div>
</div>
<?php if( !empty($this->slider)):?>
    <div class="row carousel-holder">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="margin-bottom: 20px;">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <?php $i=0; foreach ($this->slider as $p): 
                            $p['image'] = base64_encode($p['image']);
                            $p['image_name'] = pathinfo($p['image_name'], PATHINFO_EXTENSION);
                    ?>
                        <div class="item <?= $i==0?"active":"" ?>">
                            <img class="slide-image" src="data:image/<?php echo $p['image_name'] . ' ;base64,' . $p['image'] ?>" alt="" />
                        </div>
                    <?php $i++; endforeach; ?>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>
    <div class="row">
        <?php foreach ($this->product as $p) { ?>
            <div class="col-sm-3 col-lg-3 col-md-3" style="min-height: 387.8px;">
                <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'product', "fiche" => $p['id_sell']), null, true); ?>">
                <div class="thumbnail" style="min-height: 367.8px; max-height: 367.8px;">
                    <img style="min-height: 250px; max-height: 250px;"  src="data:image/<?php echo $p['type'] . ' ;base64,' . $p['img64'] ?>" />
                    <div class="caption">
                        <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'product', "fiche" => $p['id_sell']), null, true); ?>">
                        <h4 class="pull-right"><?php echo $p['price'] . " €"; ?></h4>
                        <h4><?php echo $p['title']; ?>
                        </h4></a>
                        <p><?php echo $p['description_courte']; ?></p>
                    </div>
                </div>
                </a>
            </div>
        <?php } ?>
    </div>
</div>