<div class="container">
    <div class="row">
        <!-- You can make it whatever width you want. I'm making it full width
             on <= small devices and 4/12 page width on >= medium devices -->
        <!--  <div class="col-xs-12 col-md-4">-->
        <div class="col-xs-12 col-md-4" ></div>
        <div class="col-xs-12 col-md-4" style="font-size: 12pt; line-height: 2em;">
            <!-- CREDIT CARD FORM STARTS HERE -->
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading display-table" >
                    <div class="row display-tr" >
                        <h3 class="panel-title display-td" >Payment Details</h3>
                        <div class="display-td" >                            
                            <img class="img-responsive pull-right" src="http://i76.imgup.net/accepted_c22e0.png">
                        </div>
                    </div>                    
                </div>
                <div class="panel-body">
                    <form role="form" id="payment-form">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="cardNumber">N° de carte</label>
                                    <div class="input-group">
                                        <input 
                                            type="tel"
                                            class="form-control"
                                            name="cardNumber"
                                            placeholder="Valid Card Number"
                                            autocomplete="cc-number"
                                            required autofocus 
                                            />
                                        <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                    </div>
                                </div>                            
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div class="form-group">
                                    <label for="cardExpiry"><span class="hidden-xs">date d'expiration</span><span class="visible-xs-inline">EXP</span></label>
                                    <div class="col-xs-3">
                                        <input   type="tel"  class="form-control"  name="cardExpiry" placeholder="MM" autocomplete="cc-exp"required />
                                    </div>
                                    <div class="col-xs-1">/</div>
                                    <div class="col-xs-3">
                                        <input   type="tel"  class="form-control"  name="cardExpiry" placeholder="AA" autocomplete="cc-exp"required />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div class="form-group">
                                    
                                    <label for="cardCVC">Cryptogramme visuel</label>
                                    <input 
                                        type="tel" 
                                        class="form-control"
                                        name="cardCVC"
                                        placeholder=""
                                        autocomplete="cc-csc"
                                        required
                                        />
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12">
                                <button class="btn btn-success btn-lg btn-block" type="submit">Valider le paiment</button>
                            </div>
                        </div>
                        <div class="row" style="display:none;">
                            <div class="col-xs-12">
                                <p class="payment-errors"></p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>            
            <!-- CREDIT CARD FORM ENDS HERE -->


        </div>                    
    </div>
</div>
