<form method="POST" action="<?php echo $this->url(array('controller' => 'user', 'action' => 'article', 'type' => 'ajout'), null, true); ?>" enctype="multipart/form-data" >
    Title : <input type="text" name="title" />
    <br/>
    Image : <input type="file" name="image" enctype="multipart/form-data"/>
    <input type="hidden" name="MAX_FILE_SIZE" value="6000" />
    Quantité : <input type="text" name="quantity" />
    <br/>
    category: <select name="category" >
        <?php foreach ($this->category as $value): ?>
            <option value="<?= $value['id_category']; ?>"><?= $value['label_category']; ?></option>
        <?php endforeach; ?>
    </select>
    Sous category: <select name="category" >
        <?php foreach ($this->souscategory as $value): ?>
            <option value="<?= $value['id_category']; ?>"><?= $value['parent'] . '-' . $value['label_category']; ?></option>
        <?php endforeach; ?>
    </select>

    <br/>
    Prix : <input type="text" name="price" />
    <br/>
    Description courte : <textarea name="descritptionCourt" id="" height="50px" cols="30" ></textarea>
    <br/>
    Description détaillé : <textarea name="descritption" id="" cols="30" rows="10"></textarea>
    <input type="submit" value="valider"/>
</form>


<?php if (count($this->articles) > 0) { ?>

    <div class="container">

        <hgroup class="mb20">
            <h1>Vos articles mise en vente</h1>

            <h3><strong > 
                    <?php
                    if (count($this->articles) == 1) {
                        echo count($this->articles) . " article";
                    } else {
                        echo count($this->articles) . " articles";
                    }
                    ?>
                </strong></h3>								
        </hgroup>

        <section class="col-xs-12 col-sm-6 col-md-12">

            <?php foreach ($this->articles as $value) { ?>
                <article class="search-result row">
                    <div class="col-xs-12 col-sm-12 col-md-3">
                        <a href="#" title="Lorem ipsum" class="thumbnail"><img src="data:image/<?= $value['name_image'] . ';base64,' . $value['image'] ?>" alt="" /></a>

                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-2">
                        <ul class="meta-search">
                            <li><i class="glyphicon glyphicon-calendar"></i> <span><?php echo substr($value['dt_creation'], 0, -8); ?></span></li>
                            <li><i class="glyphicon glyphicon-time"></i> <span><?php echo substr($value['dt_creation'], 10, -3); ?></span></li>
                            <li><i class="glyphicon glyphicon-tags"></i> <span>
                                <?php 
                                 foreach ($this->category as $c) {
                                if ($c['id_category'] == $value['parent']) {
                                    echo $c['label_category']." - ";
                                }
                            }
                                echo $value['label_category']; ?>
                                </span></li>
                            <li><i class="glyphicon glyphicon-euro"></i> <span><?php echo number_format($value['price'], 2, ',', ' ') . " €"; ?></span></li>
                            <li><i class="glyphicon glyphicon-shopping-cart"></i><span><?php echo $value['quantity'] . " en stock"; ?></span></li>
                            <?php
                           
                            ?>
                        </ul>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-7">
                        <h3><a href="#" title=""><?php echo $value['title']; ?></a></h3>
                        <p><?php echo $value['description']; ?></p>	

                        <span class="plus"><a href="<?= $this->url(array('controller' => 'article', 'action' => 'modify', 'fiche' => $value['id_sell']), null, true); ?>" title="Lorem ipsum"><i class="glyphicon glyphicon glyphicon-wrench"></i></a></span>
                    </div>
                    <span class="clearfix borda"></span>
                </article>
            <?php } ?>

        </section>

    </div>
<?php }
?>
