
<!-----Gestion du nombre de produit attente / valider / refuser---------->
<?php
$attente = 0;
$valider = 0;
$refuser = 0;
$vendu = 0;
$historique = 0;
if (count($this->articles) > 0) {
    foreach ($this->articles as $value) {
        if ($value['is_checked'] == "0") {
            $attente++;
        } elseif ($value['is_checked'] == "1") {
            $valider++;
        } elseif ($value['is_checked'] == "2") {
            $refuser++;
        }
    }
}
$historique = count($this->command);
$vendu = count($this->commandVente);
?>
<!----------------FIN--------------------------------------------->

<div class="container-fluid">		
    <div class="col-md-12">
        <ul id="myTab" class="nav nav-tabs nav_tabs" style="margin-right: -17px;">
            <li class="active"><a href="#service-zero" data-toggle="tab">Créer un article</a></li>
            <li><a href="#service-two" data-toggle="tab">Article(s) validé (<?= $valider; ?>)</a></li>
            <li><a href="#service-one" data-toggle="tab">Article(s) en attente de validation (<?= $attente; ?>)</a></li>
            <li><a href="#service-three" data-toggle="tab">Article(s) refusé (<?= $refuser; ?>)</a></li>
            <li><a href="#service-four" data-toggle="tab">Vente effectuée (<?= $vendu; ?>)</a></li>
            <li><a href="#service-five" data-toggle="tab">Historique commande (<?= $historique; ?>)</a></li>

        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="service-zero">
                <?php include 'createProduct.phtml'; ?>
            </div>
            <div class="tab-pane fade" id="service-one">
                <?php if (count($this->articles) > 0) { ?>
                    <div class="container">
                        <hgroup class="mb20">
                            <h3><strong > 
                                    <?php
                                    if ($attente == 0) {
                                        echo "Aucun article en attente";
                                    } else {
                                        echo $attente . " article(s)";
                                    }
                                    ?>
                                </strong></h3>								
                        </hgroup>

                        <section class="col-xs-12 col-sm-6 col-md-12">

                            <?php
                            foreach ($this->articles as $value) {
                                if ($value['is_checked'] == "0") {
                                    ?>
                                    <article class="search-result row">
                                        <div class="col-xs-12 col-sm-12 col-md-3">
                                            <a href="#" title="Lorem ipsum" class="thumbnail"><img src="data:image/<?= $value['name_image'] . ';base64,' . $value['image'] ?>" alt="" /></a>

                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-2">
                                            <ul class="meta-search">
                                                <li><i class="glyphicon glyphicon-calendar"></i> <span><?php echo substr($value['dt_creation'], 0, -8); ?></span></li>
                                                <li><i class="glyphicon glyphicon-tags"></i> <span>
                                                        <?php
                                                        foreach ($this->category as $c) {
                                                            if ($c['id_category'] == $value['parent']) {
                                                                echo $c['label_category'] . " - ";
                                                            }
                                                        }
                                                        echo $value['label_category'];
                                                        ?>
                                                    </span></li>
                                                <li><i class="glyphicon glyphicon-euro"></i> <span><?php echo number_format($value['price'], 2, ',', ' ') . " €"; ?></span></li>
                                                <li><i class="glyphicon glyphicon-shopping-cart"></i><span><?php echo $value['quantity'] . " en stock"; ?></span></li>
                                                <?php ?>
                                            </ul>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-7">
                                            <h3><a href="#" title=""><?php echo $value['title']; ?></a></h3>
                                            <p><?php echo $value['description']; ?></p>	

                                            <?php if ($value['quantity'] < 1): ?>
                                                <form method="POST" action="<?= $this->url(array('controller' => 'user', 'action' => 'article', 'type' => 'update'), null, true); ?>">
                                                    Prix :<input type="text" name="price" />Qt :<input type="text" name="quantity" /><input type="hidden" value="<?= $value['id_sell'] ?>" name="idSell" /><input type="submit" />
                                                </form>
                                            <?php endif; ?>
                                            <?php if ($value['is_checked'] == 0): ?>
                                                <span class="plus"><a href="<?= $this->url(array('controller' => 'article', 'action' => 'modify', 'fiche' => $value['id_sell']), null, true); ?>" title="Lorem ipsum"><i class="glyphicon glyphicon glyphicon-wrench"></i></a></span>
                                            <?php endif; ?>
                                        </div>
                                        <span class="clearfix borda"></span>
                                    </article>
                                    <?php
                                }
                            }
                            ?>
                        </section>

                    </div>
                <?php } ?>
            </div>
            <div class="tab-pane fade" id="service-two">
                <?php if (count($this->articles) > 0) { ?>
                    <div class="container">
                        <hgroup class="mb20">
                            <h3><strong > 
                                    <?php
                                    if ($valider == 0) {
                                        echo "Aucun article validé";
                                    } else {
                                        echo $valider . " article(s)";
                                    }
                                    ?>
                                </strong></h3>								
                        </hgroup>

                        <section class="col-xs-12 col-sm-6 col-md-12">

                            <?php
                            foreach ($this->articles as $value) {
                                if ($value['is_checked'] == "1") {
                                    ?>
                                    <article class="search-result row">
                                        <div class="col-xs-12 col-sm-12 col-md-3">
                                            <a href="#" title="Lorem ipsum" class="thumbnail"><img src="data:image/<?= $value['name_image'] . ';base64,' . $value['image'] ?>" alt="" /></a>

                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-2">
                                            <ul class="meta-search">
                                                <li><i class="glyphicon glyphicon-calendar"></i><span><?php echo substr($value['dt_creation'], 0, -8); ?></span></li>
                                                <li><i class="glyphicon glyphicon-tags"></i> <span>
                                                        <?php
                                                        foreach ($this->category as $c) {
                                                            if ($c['id_category'] == $value['parent']) {
                                                                echo $c['label_category'] . " - ";
                                                            }
                                                        }
                                                        echo $value['label_category'];
                                                        ?>
                                                    </span></li>
                                                <li><i class="glyphicon glyphicon-euro"></i> <span><?php echo number_format($value['price'], 2, ',', ' ') . " €"; ?></span></li>
                                                <li><i class="glyphicon glyphicon-shopping-cart"></i><span><?php echo $value['quantity'] . " en stock"; ?></span></li>
                                                <?php ?>
                                            </ul>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-7">
                                            <h3><a href="#" title=""><?php echo $value['title']; ?></a></h3>
                                            <p><?php echo $value['description']; ?></p>	

                                            <?php if ($value['quantity'] < 1): ?>
                                                <form method="POST" action="<?= $this->url(array('controller' => 'user', 'action' => 'article', 'type' => 'update'), null, true); ?>">
                                                    Prix :<input type="text" name="price" />Qt :<input type="text" name="quantity" /><input type="hidden" value="<?= $value['id_sell'] ?>" name="idSell" /><input type="submit" />
                                                </form>
                                            <?php endif; ?>
                                            <?php if ($value['is_checked'] == 0): ?>
                                                <span class="plus"><a href="<?= $this->url(array('controller' => 'article', 'action' => 'modify', 'fiche' => $value['id_sell']), null, true); ?>" title="Lorem ipsum"><i class="glyphicon glyphicon glyphicon-wrench"></i></a></span>
                                            <?php endif; ?>
                                        </div>
                                        <span class="clearfix borda"></span>
                                    </article>
                                    <?php
                                }
                            }
                            ?>
                        </section>
                    </div>
                <?php } ?>
            </div>
            <div class="tab-pane fade" id="service-three">
                <?php if (count($this->articles) > 0) { ?>
                    <div class="container">
                        <hgroup class="mb20">
                            <h3><strong > 
                                    <?php
                                    if ($refuser == 0) {
                                        echo "Aucun article refusé";
                                    } else {
                                        echo $refuser . " article(s)";
                                    }
                                    ?>
                                </strong></h3>								
                        </hgroup>

                        <section class="col-xs-12 col-sm-6 col-md-12">

                            <?php
                            foreach ($this->articles as $value) {
                                if ($value['is_checked'] == "2") {
                                    ?>
                                    <article class="search-result row">
                                        <div class="col-xs-12 col-sm-12 col-md-3">
                                            <a href="#" title="Lorem ipsum" class="thumbnail"><img src="data:image/<?= $value['name_image'] . ';base64,' . $value['image'] ?>" alt="" /></a>

                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-2">
                                            <ul class="meta-search">
                                                <li><i class="glyphicon glyphicon-calendar"></i> <span><?php echo substr($value['dt_creation'], 0, -8); ?></span></li>

                                                <li><i class="glyphicon glyphicon-tags"></i> <span>
                                                        <?php
                                                        foreach ($this->category as $c) {
                                                            if ($c['id_category'] == $value['parent']) {
                                                                echo $c['label_category'] . " - ";
                                                            }
                                                        }
                                                        echo $value['label_category'];
                                                        ?>
                                                    </span></li>
                                                <li><i class="glyphicon glyphicon-euro"></i> <span><?php echo number_format($value['price'], 2, ',', ' ') . " €"; ?></span></li>
                                                <li><i class="glyphicon glyphicon-shopping-cart"></i><span><?php echo $value['quantity'] . " en stock"; ?></span></li>
                                                <?php ?>
                                            </ul>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-7">
                                            <h3><a href="#" title=""><?php echo $value['title']; ?></a></h3>
                                            <p><?php echo $value['description']; ?></p>	

                                            <?php if ($value['quantity'] < 1): ?>
                                                <form method="POST" action="<?= $this->url(array('controller' => 'user', 'action' => 'article', 'type' => 'update'), null, true); ?>">
                                                    Prix :<input type="text" name="price" />Qt :<input type="text" name="quantity" /><input type="hidden" value="<?= $value['id_sell'] ?>" name="idSell" /><input type="submit" />
                                                </form>
                                            <?php endif; ?>
                                            <?php if ($value['is_checked'] == 0): ?>
                                                <span class="plus"><a href="<?= $this->url(array('controller' => 'article', 'action' => 'modify', 'fiche' => $value['id_sell']), null, true); ?>" title="Lorem ipsum"><i class="glyphicon glyphicon glyphicon-wrench"></i></a></span>
                                            <?php endif; ?>
                                        </div>
                                        <span class="clearfix borda"></span>
                                    </article>
                                    <?php
                                }
                            }
                            ?>
                        </section>

                    </div>
                <?php } ?>
            </div>
            <div class="tab-pane fade" id="service-four">
                <hgroup class="mb20">
                    <h3><strong > 
                            Vente(s) effectuée(s)
                        </strong></h3>								
                </hgroup>
                <section class="col-xs-12 col-sm-6 col-md-12">
                    <div class="container">
                        <div class="row">
                            <div class="span12">
                                <?php
                                $compteurCommand = 0;
                                foreach ($this->commandVente as $cv) {
                                    $quantite = 0;
                                    $totalCommande = 0;
                                    foreach ($this->complementCommande as $complement) {

                                        if ($cv['id_command'] == $complement['id_command']) {
                                            $quantite += $complement['quantity'];
                                            $totalCommande += $complement['quantity'] * $complement['price'];
                                        }
                                    }
                                    ?>
                                    <div class="accordion-toggle " data-toggle="collapse" href="#commandeVente<?php echo $cv['id_command']; ?>">
                                        <table class="table table-striped">
                                            <?php if ($compteurCommand == 0) { ?>
                                                <thead>
                                                    <tr>
                                                        <td>N° Commmande</td>
                                                        <td>Montant Encaissé</td>
                                                        <td>Nombre de produit</td>
                                                        <td>Adresse du client</td>
                                                        <td>Email</td>      
                                                        <td>Date</td>
                                                    </tr>
                                                </thead>
                                            <?php } $compteurCommand++; ?>
                                            <tbody>
                                                <?php
                                                foreach ($this->infoBuyer as $i) {
                                                    if ($i['id_command'] == $cv['id_command']) {
                                                        ?>
                                                        <tr>
                                                            <td style="width:155.817px;">N° <?php echo $cv['id_command']; ?></td>
                                                            <td style="width:169.033px;"><?php echo number_format($totalCommande, 2, ',', ' '); ?> €</td>
                                                            <td style="width:175.633px;"><?= $quantite; ?></td>
                                                            <td style="width:257.5px;"><?= $i['address_user']; ?></td>
                                                            <td style="width:158.467px;"><?= $i['mail_user']; ?></td>                                                    
                                                            <td style="width:116.217px;"><?php
                                                                $explode = explode("-", substr($i['dt_command'], 0, -9));
                                                                echo $explode[2] . "/" . $explode[1] . "/" . $explode[0];
                                                                ?></td>
                                                        </tr>
                                                        <?php
                                                    }
                                                }
                                                ?>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div id = "commandeVente<?php echo $cv['id_command']; ?>" class = "accordion-body collapse">
                                        <div class = "accordion-inner">
                                            <table class = "table table-striped table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>Nom du produit</th>
                                                        <th>Quantité</th>
                                                        <th>Prix Unitaire</th>
                                                        <th>Total</th>

                                                    </tr>
                                                </thead>
                                                <tbody>

                                                    <?php
                                                    foreach ($this->detailCommand as $c) {
                                                        if ($c['id_command'] == $cv['id_command']) {
                                                            ?>
                                                            <tr>
                                                                <td><?= $c['title']; ?></td>
                                                                <td><?= $c['quantity']; ?></td>
                                                                <td><?php echo number_format($c['price'], 2, ',', ' '); ?> €</td>
                                                                <td><?php echo number_format($c['quantity'] * $c['price'], 2, ',', ' '); ?> €</td>
                                                            </tr>
                                                        <?php }
                                                    }
                                                    ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
<?php } ?>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
<?php if ($historique != 0) { ?>
                <div class="tab-pane fade" id="service-five">
                    <hgroup class="mb20">
                        <h3><strong>Historique commande</strong></h3>								
                    </hgroup>
                    <section class="col-xs-12 col-sm-6 col-md-12">
                        <div class="container">
                            <div class="row">
                                <div class="span12">
                                    <?php
                                    $compteurCommand = 0;
                                    $nbProduct = 0;
                                    $montantTotalCommand = 0;
                                    ?>
                                    <?php
                                    foreach ($this->command as $c) {
                                        $nbProduct = 0;
                                        $montantTotalCommand = 0;
                                        foreach ($this->commandeLine as $cl) {
                                            if ($cl['id_command'] == $c['id_command']) {
                                                $nbProduct += $cl['quantity'];
                                                $montantTotalCommand += $cl['quantity'] * $cl['price'];
                                            }
                                        }
                                        ?>
                                        <div class="accordion-toggle " data-toggle="collapse" href="#<?= $c['id_command']; ?>">

                                            <table class="table table-striped">
        <?php if ($compteurCommand == 0) { ?>
                                                    <thead>
                                                        <tr>
                                                            <td>N° Commmande</td>
                                                            <td>Montant Total</td>
                                                            <td>Nombre de produit</td>
                                                            <td>Date</td>
                                                        </tr>
                                                    </thead>
        <?php } $compteurCommand++; ?>

                                                <tbody>

                                                    <tr>
                                                        <td  style="width: 312.35px;">N° <?= $c['id_command']; ?></td>
                                                        <td style="width: 267.35px;"><?= number_format($montantTotalCommand, 2, ',', ' '); ?> €</td>
                                                        <td style="width: 352.067px;"><?= $nbProduct; ?></td>
                                                        <td style="width: 338.333px;"><?php
                                                            $explode = explode("-", substr($c['dt_command'], 0, -9));
                                                            echo $explode[2] . "/" . $explode[1] . "/" . $explode[0];
                                                            ?></td>
                                                    </tr>

                                                </tbody>
                                            </table>

                                        </div>
                                        <div id="<?= $c['id_command']; ?>" class="accordion-body collapse">
                                            <div class="accordion-inner">
                                                <table class="table table-striped table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th>Nom du produit</th>
                                                            <th>Vendeur</th>

                                                            <th>Quantité</th>
                                                            <th>Prix Unitaire</th>
                                                            <th>Total</th>

                                                        </tr>
                                                    </thead>   
                                                    <tbody>
                                                        <?php
                                                        foreach ($this->commandeLine as $cl) {
                                                            if ($cl['id_command'] == $c['id_command']) {
                                                                ?>
                                                                <tr>
                                                                    <td><?= $cl['title']; ?></td>
                                                                    <td><?= $cl['login_user'] . " - " . $cl['mail_user']; ?></td>

                                                                    <td><?= $cl['quantity']; ?></td>
                                                                    <td><?= number_format($cl['price'], 2, ',', ' '); ?> €</td>
                                                                    <td><?= $cl['price'] * $cl['quantity']; ?> €</td>
                                                                </tr>
                                                                <?php
                                                            }
                                                        }
                                                        ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
<?php } ?>

        </div>
    </div>
    <hr>
</div>

