<div class = "col-md-2"></div>
<div class = "col-md-8">
    <div class="wrapper">
        <form class="form-signindefault" style="max-width: 768px!important;" method="POST"action="<?php echo $this->url(array('controller' => 'user', 'action' => 'article', 'type' => 'ajout'), null, true); ?>" enctype="multipart/form-data"  name="Login_Form" class="form-signin">       
            <h3 class="form-signin-heading"><center>Créer votre produit</center></h3>
            <div class="stepwizard">
                <div class="stepwizard-row setup-panel">
                    <div class="stepwizard-step">
                        <a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
                        <p>Informations Générales</p>
                    </div>
                    <div class="stepwizard-step">
                        <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                        <p>Caractéristiques</p>
                    </div>
                    <div class="stepwizard-step">
                        <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                        <p>Récaptitulatif</p>
                    </div>
                </div>
            </div>
            <hr class="colorgraph">
            <div class="row setup-content" id="step-1">
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <h3><center>Informations Générales</center></h3>
                        <div class="form-group">
                            <label class="control-label">Titre du produit</label>
                            <input  maxlength="50" type="text" name="productTitle" required="required" class="form-control" placeholder="Le titre de votre produit" autocomplete="off"/>
                        </div>
                        <div class="form-group">

                            <label class="control-label">Image du produit</label>
                            <span class="file-input btn btn-block btn-primary btn-file">
                                Uploader l'image de votre produit <input type="file" multiple name="image" required="required">
                            </span>
                        </div>
                        <hr class="colorgraph">
                        <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Suivant</button>
                    </div>
                </div>
            </div>
            <div class="row setup-content" id="step-2">
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <h3> <center>Caractéristiques</center></h3>
                        <div class="form-group">
                            <label class="control-label">Description courte (max: 100 caractères)</label>
                            <input maxlength="100" type="text" name="productDescritptionCourte" required="required" class="form-control" placeholder="Description courte" />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Description longue</label>
                            <textarea name="descritption" id="productDescription" id="toto" ></textarea>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <label class="control-label">Quantité</label>
                                <input max="999" min="0" name="productQuantite" required="required" class="form-control" placeholder=""  />  </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <label class="control-label">Prix</label>
                                <div class="input-group">
                                    <span class="input-group-addon">€</span>
                                    <input data-fv-field="amount" class="form-control" name="productPrix" max="999999.99" min="0"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <table class="table table-bordered table-hover">
                                <tr><td class="info"><center>Rubrique</center></td></tr>
                                <?php foreach ($this->category as $value): ?>
                                    <tr><td class="clickListRubrique active" data="category-<?= $value['id_category']; ?>"><center><?= $value['label_category']; ?></center></td></tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <?php
                            foreach ($this->category as $value) {
                                ?> 
                                <table style="display:none;" class="table table-bordered table-hover sous-category" id="category-<?= $value['id_category']; ?>">
                                    <tr><td class="info"><center>Sous Rubrique : <?= $value['label_category']; ?></center></td></tr>
                                    <?php
                                    foreach ($this->souscategory as $key => $ssrubrique) {
                                        if ($ssrubrique['parent'] == $value['id_category']) {
                                            ?>
                                            <tr>
                                                <td class="active select-sous-category" data="<?= $ssrubrique['id_category']; ?>"><?= $ssrubrique['label_category']; ?></td>
                                            </tr>
                                            <?php
                                        }
                                    }
                                    ?>
                                </table>
                            <?php }
                            ?>
                            <span id="sous-rubrique-choisi" sous-rubrique="" id-sous-rubrique="" rubrique="" style="display:none;"></span>
                            <input type="hidden" name="sous-rubrique-hidden" id="sous-rubrique-cacher" value="">
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <hr class="colorgraph">
                            <div class="row">
                                <div class="col-xs-12">
                                    <button class="btn btn-lg btn-primary btn-block nextBtn" id="reviewProduct"value="Login" type="button">Voyons ensemble votre produit</button>  			
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row setup-content" id="step-3">
                <div class="col-xs-12">
                    <div class="col-md-12">
                        <h3><center>Voici votre produit: <span id="recapTitle"></span></center></h3>
                        <div class="container-fluid">
                            <div class="content-wrapper">	
                                <div class="item-container">	
                                    <div class="col-md-5 service-image-left">
                                        <center>
                                            <img src="http://lorempixel.com/261/261/" />
                                        </center>
                                        <br /><br />
                                        <div class="panel panel-primary">
                                            <div class="panel-heading">
                                                <h3 class="panel-title"></h3>
                                            </div>
                                            <div class="panel-body"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-7">
                                        <div class="product-desc" id="recapDescriptionCourte"></div>
                                        <div class="row">
                                            <div class="product-price" id="recapPrix"></div>
                                            <div class="product-quantity" id="recapQuantite"></div>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <hr class="colorgraph">
                            <div class="row">
                                <div class="col-xs-12">
                                    <button class="btn btn-lg btn-primary btn-block nextBtn" value="Login" type="button">Mettre en ligne</button>  			
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>		
    </div>
</div>
