<div class = "col-md-8">
    <div class="wrapper">

        <form class="form-signindefault" style="max-width: 768px!important;" action="<?php echo $this->url(array('controller' => 'user', 'action' => 'index', 'type' => 'signin'), null, true); ?>" method="post" name="Login_Form" class="form-signin">       
            <h3 class="form-signin-heading"><center>Créer votre produit</center></h3>
            <div class="stepwizard">
                <div class="stepwizard-row setup-panel">
                    <div class="stepwizard-step">
                        <a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
                        <p>Informations Générales</p>
                    </div>
                    <div class="stepwizard-step">
                        <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                        <p>Caractéristiques</p>
                    </div>
                    <div class="stepwizard-step">
                        <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                        <p>Récaptitulatif</p>
                    </div>
                </div>
            </div>
            <hr class="colorgraph">


            <form role="form">
                <div class="row setup-content" id="step-1">
                    <div class="col-xs-12">
                        <div class="col-md-12">
                            <h3>Informations Générales</h3>
                            <div class="form-group">
                                <label class="control-label">Titre du produit</label>
                                <input  maxlength="100" type="text" required="required" class="form-control" placeholder="Le titre de votre produit"  />
                            </div>
                            <div class="form-group">

                                <label class="control-label">Image du produit</label>
                                <span class="file-input btn btn-block btn-primary btn-file">
                                    Uploader l'image de votre produit <input type="file" multiple required="required">
                                </span>

                            </div>
                             <hr class="colorgraph">
                            <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Suivant</button>
                        </div>
                    </div>
                </div>
                <div class="row setup-content" id="step-2">
                    <div class="col-xs-12">
                        <div class="col-md-12">
                            <h3> Caractéristiques</h3>
                            <div class="form-group">
                                <label class="control-label">Description courte (max: 140 caractères)</label>
                                <input maxlength="140" type="text" required="required" class="form-control" placeholder="Description courte" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Description longue</label>
                                 <textarea></textarea>
                                
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Prix</label>
                                    <input maxlength="8" type="text" required="required" class="form-control" placeholder="1 €"  />  </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Quantité</label>
                                    <input maxlength="10" type="tel" required="required" class="form-control" placeholder="10"  />
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">
                                <table class="table table-bordered table-hover">
                                    <tr><td class="info"><center>Rubrique</center></td></tr>
                                    <?php foreach ($this->category as $value): ?>
                                        <tr><td class="clickListRubrique active" data="category-<?= $value['id_category']; ?>"><center><?= $value['label_category']; ?></center></td></tr>
                                    <?php endforeach; ?>
                                </table>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6">

                                <?php
                                foreach ($this->category as $value) {
                                    ?> 
                                    <table style="display:none;" class="table table-bordered table-hover sous-category" id="category-<?= $value['id_category']; ?>">
                                        <tr><td class="info"><center>Sous Rubrique : <?= $value['label_category']; ?></center></td></tr>
                                        <?php
                                        foreach ($this->souscategory as $key => $ssrubrique) {
                                            if ($ssrubrique['parent'] == $value['id_category']) {
                                                ?>
                                                <tr>
                                                    <td class="active select-sous-category" data="<?= $ssrubrique['id_category']; ?>"><?= $ssrubrique['label_category']; ?></td>
                                                </tr>
                                                <?php
                                            }
                                        }
                                        ?>
                                    </table>
                                <?php }
                                ?>

                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <hr class="colorgraph">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <button class="btn btn-lg btn-primary btn-block nextBtn" value="Login" type="button">Voyons ensemble votre produit</button>  			
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row setup-content" id="step-3">
                    <div class="col-xs-12">
                        <div class="col-md-12">
                            <h3> Step 3</h3>
                            <button class="btn btn-success btn-lg pull-right" type="submit">Finish!</button>
                        </div>
                    </div>
                </div>
            </form>
        </form>			
    </div>
</div>
