<div class = "col-md-6">
    <div class="wrapper">
        <form action="" method="post" name="Login_Form" class="form-signin">       
            <h3 class="form-signin-heading">Identifiez vous pour poursuivre</h3>
            <hr class="colorgraph"><br>
            <div class="form-group">
                <input type="text" name="Username" id="display_name" class="form-control input-lg" placeholder="Email" tabindex="1" required=""/>
            </div>
            <div class="form-group">
                <input type="password" name="Password" id="email" class="form-control input-lg" placeholder="Mot de passe" tabindex="2" required=""/>
            </div>		  
            <hr class="colorgraph">
            <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">Se connecter</button>  			
        </form>			
    </div>
</div>
<div class="col-md-6">

    <div class="wrapper">
        <form role="form" class="form-signin" id="passwordForm">
            <h2> Vous êtes nouveau client <small>Inscrivez vous gratuitement</small></h2>
            <hr class="colorgraph">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="text" name="last_name" id="first_name" class="form-control input-lg" placeholder="Nom" tabindex="1" required=""/>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="text" name="first_name" id="last_name" class="form-control input-lg" placeholder="Prénom" tabindex="2" required=""/>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="email" name="email" id="display_name" class="form-control input-lg" placeholder="Email" tabindex="3" required=""/>
            </div>
            <div class="form-group">
                <input type="text" name="login" id="email" class="form-control input-lg" placeholder="Login" tabindex="4" required=""/>
            </div>

            <div class="form-group">
                <div class="form-group">
                    <input type="password" name="password1" id="password1" class="form-control input-lg" placeholder="Mot de passe" tabindex="5" autocomplete="off" required=""/>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <span id="8char" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 8 caractères<br>
                    <span id="ucase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 1 lettre majuscule
                </div>
                <div class="col-sm-6">
                    <span id="lcase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 1 lettre minuscule<br>
                    <span id="num" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 1 chiffre
                </div>
            </div>
            <div class="form-group">
                <input type="password" name="password2" id="password2" class="form-control input-lg" placeholder="Confirmez votre mot de passe" autocomplete="off" tabindex="6" required=""/>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <span id="pwmatch" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> Mot de passe identique
                </div>
            </div>




            <hr class="colorgraph">
            <div class="row">
                <div class="col-xs-12 col-md-6"><input type="submit" value="S'incrire" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
                <div class="col-xs-12 col-md-6"><a href="#" class="btn btn-success btn-block btn-lg">S'incrire</a></div>
            </div>
        </form>
    </div>
</div>
