<div class="wrapper signin">

    <form action="<?php echo $this->url(array('controller' => 'user', 'action' => 'index' ,'type' => 'signin'),null,true); ?>" method="POST" name="Login_Form" class="form-signin">       
        <h3 class="form-signin-heading">Connectez-vous</h3>
        <hr class="colorgraph"><br>

        <input type="text" class="form-control" name="login" placeholder="Login" required="" autofocus="" />
        <input type="password" class="form-control" name="password" placeholder="Mot de passe" required=""/>     		  

        <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="submit">Login</button>  			
    </form>			
</div>



<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Please sign up for Bootsnipp <small>It's free!</small></h3>
    </div>
    <div class="panel-body">
        <form role="form" action="<?php echo $this->url(array('controller' => 'user', 'action' => 'index' ,'type' => 'signup'),null,true); ?>" method="POST">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="text" name="first_name" id="first_name" class="form-control input-sm" placeholder="First Name">
                    </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address">
            </div>

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
                    </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="text" name="login" id="password" class="form-control input-sm" placeholder="Login">
                    </div>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <div class="form-group">
                        <input type="tel" name="phone" id="password_confirmation" class="form-control input-sm" placeholder="Phone">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="text" name="address" id="email" class="form-control input-sm" placeholder="Address">
            </div>

            <input type="submit" value="Register" class="btn btn-info btn-block">

        </form>
    </div>
</div>
