<?php

//Base de données
define('DB_NAME_TELEMAQUE', 'telemaque');

//Tables
define('DB_TABLE_ARTICLE', DB_NAME_TELEMAQUE . '.article');
define('DB_TABLE_CATEGORY', DB_NAME_TELEMAQUE . '.category');
define('DB_TABLE_USER', DB_NAME_TELEMAQUE . '.user');
define('DB_TABLE_RANK', DB_NAME_TELEMAQUE . '.rank');
define('DB_TABLE_SELL', DB_NAME_TELEMAQUE . '.sell');
define('DB_TABLE_IMAGE', DB_NAME_TELEMAQUE . '.image');
define('DB_TABLE_IMAGE_WEBSITE', DB_NAME_TELEMAQUE . '.image_website');

